import { MODES, THEMES, type Mode, type Tokens } from "./tokens";

function block(selector: string, mode: Mode): string {
  const t: Tokens = THEMES[mode];
  const lines = Object.entries(t).map(([k, v]) => `  --${k}: ${v};`);
  lines.push(`  color-scheme: ${mode};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

/** The full contents of styles/themes.css. */
export function buildThemesCss(): string {
  const out: string[] = [
    "/* GENERATED by `npm run themes:build` from lib/theme/tokens.ts. Do not edit by hand. */",
    "",
    "/* Fallback before the theme script runs (or without JavaScript): follow the OS mode. */",
    block(":root", "light"),
    `@media (prefers-color-scheme: dark) {\n${block(":root:not([data-mode])", "dark")
      .split("\n")
      .map((l) => "  " + l)
      .join("\n")}\n}`,
    "",
    "/* Light and dark. Works on <html> and on any nested element (the style guide previews both). */",
  ];
  for (const mode of MODES) out.push(block(`[data-mode="${mode}"]`, mode));
  return out.join("\n") + "\n";
}
