import { ERAS, METAL_GRADIENT, MODES, THEMES, type Era, type Mode, type Tokens } from "./tokens";

/** A plain, generic cog (not the Oilers gear crest) tiled faintly behind Gear-theme pages. */
function gearPattern(color: string): string {
  const teeth = Array.from({ length: 8 }, (_, i) => {
    const a = i * 45;
    return `<rect x='56' y='22' width='16' height='16' rx='2' transform='rotate(${a} 64 64)'/>`;
  }).join("");
  const svg =
    `<svg xmlns='http://www.w3.org/2000/svg' width='160' height='160' viewBox='0 0 128 128'>` +
    `<g fill='none' stroke='${color}' stroke-width='2'>${teeth}<circle cx='64' cy='64' r='28'/><circle cx='64' cy='64' r='11'/></g></svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
}

function block(selector: string, era: Era, mode: Mode): string {
  const t: Tokens = THEMES[era][mode];
  const lines = Object.entries(t).map(([k, v]) => `  --${k}: ${v};`);
  lines.push(`  --metal: ${METAL_GRADIENT};`);
  lines.push(
    `  --page-pattern: ${
      era === "gear" ? gearPattern(mode === "dark" ? "rgba(255,255,255,0.028)" : "rgba(4,30,66,0.04)") : "none"
    };`,
  );
  lines.push(`  color-scheme: ${mode};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

/** The full contents of styles/themes.css. */
export function buildThemesCss(): string {
  const out: string[] = [
    "/* GENERATED by `npm run themes:build` from lib/theme/tokens.ts. Do not edit by hand. */",
    "",
    "/* Fallback before the theme script runs (or without JavaScript): Dynasty, following the OS mode. */",
    block(":root", "dynasty", "light"),
    `@media (prefers-color-scheme: dark) {\n${block(":root:not([data-mode])", "dynasty", "dark")
      .split("\n")
      .map((l) => "  " + l)
      .join("\n")}\n}`,
    "",
    "/* Era x mode. Works on <html> and on any nested element (the style guide previews all six). */",
  ];
  for (const era of ERAS) {
    for (const mode of MODES) {
      out.push(block(`[data-era="${era}"][data-mode="${mode}"]`, era, mode));
    }
  }
  return out.join("\n") + "\n";
}
